QuanLyGiaDung/Models/NhanVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int MaNV { get; set; }
        public string AnhNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SDT { get; set; }
        public string TaiKhoan { get; set; }
    }
}

QuanLyGiaDung/Controllers/NhanViensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyGiaDung.Models;
using System.IO;
using PagedList;

namespace QuanLyGiaDung.Controllers
{
    public class NhanViensController : Controller
    {
        private QuanLyGiaDung2Entities db = new QuanLyGiaDung2Entities();

        // GET: NhanViens
        public ActionResult Index(string searchString, string sortOrder, int? page)
        {


            var links = from l in db.NhanViens // lấy toàn bộ liên kết
                        select l;

            if (!String.IsNullOrEmpty(searchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
            {
                links = links.Where(s => s.TenNV.Contains(searchString)); //lọc theo chuỗi tìm kiếm
            }

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            switch (sortOrder)
            {
                // 3.1 Nếu biến sortOrder sắp giảm thì sắp giảm theo LinkName
                case "name_desc":
                    links = links.OrderByDescending(s => s.TenNV);
                    break;

                // 3.2 Mặc định thì sẽ sắp tăng
                default:
                    links = links.OrderBy(s => s.TenNV);
                    break;
            }

            if (page == null) page = 1;
            links = links.OrderBy(s => s.MaNV);
            int pageSize = 6;
            int pageNumber = (page ?? 1);

            return View(links.ToPagedList(pageNumber, pageSize)); //trả về kết quả
        }


        // GET: NhanViens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // GET: NhanViens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NhanViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase AnhNV, NhanVien nhanVien)
        {
            if (AnhNV != null)
            {
                string p = Path.Combine(Server.MapPath("~/Anh"), Path.GetFileName(AnhNV.FileName));
                AnhNV.SaveAs(p);
                nhanVien.AnhNV = AnhNV.FileName;
            }
            if (ModelState.IsValid)
            {
                db.NhanViens.Add(nhanVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhanVien);
        }

        // GET: NhanViens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: NhanViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase AnhNV, NhanVien nhanVien)
        {
            if (AnhNV != null)
            {
                string path = Path.Combine(Server.MapPath("~/Anh"), Path.GetFileName(AnhNV.FileName));
                AnhNV.SaveAs(path);
                nhanVien.AnhNV = AnhNV.FileName;
            }
            if (ModelState.IsValid)
            {
                db.Entry(nhanVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                db.NhanViens.Add(nhanVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(nhanVien);
        }

        // GET: NhanViens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: NhanViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NhanVien nhanVien = db.NhanViens.Find(id);
            db.NhanViens.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyGiaDung/Views/NhanViens/Create.cshtml
@model QuanLyGiaDung.Models.NhanVien

@{
    ViewBag.Title = "Create";
}

<h2>Tạo Mới</h2>


@using (Html.BeginForm("Create", "NhanViens", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Nhân Viên</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaNV, "Mã Nhân Viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhNV, "Ảnh Nhân Viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhNV, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.AnhNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNV,"Tên Nhân Viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh,"Ngày Sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi,"Địa Chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan,"Tài Khoản", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyGiaDung/Views/NhanViens/Delete.cshtml
@model QuanLyGiaDung.Models.NhanVien

@{
    ViewBag.Title = "Delete";
}

<h2>Xóa</h2>

<h3>Bạn có muốn xóa thông tin này</h3>
<div>
    <h4>Nhân Viên</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           Ảnh Nhân Viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhNV)
        </dd>

        <dt>
            Tên Nhân Viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            Ngày Sinh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            Địa Chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            SDT
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            Tài Khoản
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay Lại", "Index")
        </div>
    }
</div>

QuanLyGiaDung/Views/NhanViens/Details.cshtml
@model QuanLyGiaDung.Models.NhanVien

@{
    ViewBag.Title = "Details";
}

<h2>Chi Tiết</h2>

<div>
    <h4>Nhân Viên</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ảnh Nhân Viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhNV)
        </dd>

        <dt>
            Tên Nhân Viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
           Ngày Sinh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            Địa Chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            SDT
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            Tài Khoản
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh Sửa", "Edit", new { id = Model.MaNV }) |
    @Html.ActionLink("Quay Lại", "Index")
</p>

QuanLyGiaDung/Views/NhanViens/Edit.cshtml
@model QuanLyGiaDung.Models.NhanVien

@{
    ViewBag.Title = "Edit";
}

<h2>Chỉnh Sửa</h2>


@using (Html.BeginForm("Edit", "NhanViens", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Nhân Viên</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNV)

        <div class="form-group">
            @Html.LabelFor(model => model.AnhNV,"Ảnh Nhân Viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhNV, new { htmlAttributes = new { @class = "form-control",@type="file" } })
                @Html.ValidationMessageFor(model => model.AnhNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNV,"Tên Nhân Viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh,"Ngày Sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi,"Địa Chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan,"Tài Khoản", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu Lại" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay Lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyGiaDung/Views/NhanViens/Index.cshtml
@model PagedList.IPagedList<QuanLyGiaDung.Models.NhanVien>
@using PagedList.Mvc;


@{
    ViewBag.Title = "Danh Sách Nhân Viên";
}

<h2 style="text-align:center">Danh Sách Nhân Viên</h2>
<p>
    @using (Html.BeginForm())
    {
    <p>
        Tên Nhân Viên: @Html.TextBox("SearchString") <input type="submit" value="Tìm kiếm" />
    </p>
}
    <p>
        @Html.ActionLink("Tạo mới", "Create")
    </p>
 <table class="table" border="1">
        <tr>
            <th>
                Mã Nhân Viên
            </th>
            <th>
                Ảnh Nhân Viên
            </th>
            <th>
                @Html.ActionLink("Tên Nhân Viên", "Index", new { sortOrder = ViewBag.NameSortParm })
            </th>
            <th>
                Ngày Sinh
            </th>
            <th>
                Địa Chỉ
            </th>
            <th>
                SĐT
            </th>
            <th>
                Tài Khoản
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaNV)
                </td>

                <td>
                    <img src="~/Anh/@item.AnhNV" width="60px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgaySinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SDT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaiKhoan)
                </td>
                <td>
                    @Html.ActionLink("Chỉnh Sửa", "Edit", new { id = item.MaNV }) |
                    @Html.ActionLink("Chi Tiết", "Details", new { id = item.MaNV }) |
                    @Html.ActionLink("Xóa", "Delete", new { id = item.MaNV })
                </td>
            </tr>
        }

    </table>
    
    <br />
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page }))
    <!-- Kết thúc -->