QuanLyGiaDung/Controllers/DMSPsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyGiaDung.Models;
using PagedList;

namespace QuanLyGiaDung.Controllers
{
    public class DMSPsController : Controller
    {
        private QuanLyGiaDung2Entities db = new QuanLyGiaDung2Entities();

        // GET: DMSPs
        public ActionResult Index(string searchString, int? page)
        {
            var links = from l in db.DMSPs // lấy toàn bộ liên kết
                        select l;

            if (!String.IsNullOrEmpty(searchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
            {
                links = links.Where(s => s.TenDMSP.Contains(searchString)); //lọc theo chuỗi tìm kiếm
            }
            if (page == null) page = 1;
            links = links.OrderBy(x => x.TenDMSP);
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(links.ToPagedList(pageNumber, pageSize)); //trả về kết quả
        }

        // GET: DMSPs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DMSP dMSP = db.DMSPs.Find(id);
            if (dMSP == null)
            {
                return HttpNotFound();
            }
            return View(dMSP);
        }

        // GET: DMSPs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DMSPs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDMSP,TenDMSP")] DMSP dMSP)
        {
            if (ModelState.IsValid)
            {
                db.DMSPs.Add(dMSP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dMSP);
        }

        // GET: DMSPs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DMSP dMSP = db.DMSPs.Find(id);
            if (dMSP == null)
            {
                return HttpNotFound();
            }
            return View(dMSP);
        }

        // POST: DMSPs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDMSP,TenDMSP")] DMSP dMSP)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dMSP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dMSP);
        }

        // GET: DMSPs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DMSP dMSP = db.DMSPs.Find(id);
            if (dMSP == null)
            {
                return HttpNotFound();
            }
            return View(dMSP);
        }

        // POST: DMSPs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DMSP dMSP = db.DMSPs.Find(id);
            db.DMSPs.Remove(dMSP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyGiaDung/Controllers/SanPhamsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyGiaDung.Models;
using PagedList;
using System.Linq.Dynamic; // nhúng vào tập tin 
namespace QuanLyGiaDung.Controllers
{
    public class SanPhamsController : Controller
    {
        private QuanLyGiaDung2Entities db = new QuanLyGiaDung2Entities();

        // GET: SanPhams
        public ActionResult Index(string searchString, string sortOrder,  int? page, int MaDMSP = 0)
        {

            var links = from l in db.SanPhams // lấy toàn bộ liên kết
                        select l;

            var categories = from c in db.DMSPs select c;
            ViewBag.MaDMSP = new SelectList(categories, "MaDMSP", "TenDMSP"); // danh sách Category
            links = links = db.SanPhams.Include(l => l.DMSP);
            //4. Tìm kiếm theo CategoryID
            if (MaDMSP != 0)
            {
                links = links.Where(x => x.MaDMSP == MaDMSP);
            }

            if (!String.IsNullOrEmpty(searchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
            {
                links = links.Where(s => s.TenSP.Contains(searchString)); //lọc theo chuỗi tìm kiếm
            }

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            switch (sortOrder)
            {
                // 3.1 Nếu biến sortOrder sắp giảm thì sắp giảm theo LinkName
                case "name_desc":
                    links = links.OrderByDescending(s => s.TenSP);
                    break;

                // 3.2 Mặc định thì sẽ sắp tăng
                default:
                    links = links.OrderBy(s => s.TenSP);
                    break;
            }


            if (page == null) page = 1;
            links = links.OrderBy(x => x.MaSP);
            int pageSize = 6;
            int pageNumber = (page ?? 1);

            return View(links.ToPagedList(pageNumber, pageSize)); //trả về kết quả
        }

        // GET: SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaDMSP = new SelectList(db.DMSPs, "MaDMSP", "TenDMSP");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(HttpPostedFileBase AnhSP, SanPham sanpham)
        {
            if (AnhSP != null)
            {
                string p = Path.Combine(Server.MapPath("~/Anh"), Path.GetFileName(AnhSP.FileName));
                AnhSP.SaveAs(p);
                sanpham.AnhSP = AnhSP.FileName;
            }
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(sanpham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sanpham);
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDMSP = new SelectList(db.DMSPs, "MaDMSP", "TenDMSP", sanPham.MaDMSP);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(HttpPostedFileBase AnhSP, SanPham sanPham)
        {
            if (AnhSP != null)
            {
                string path = Path.Combine(Server.MapPath("~/Anh"), Path.GetFileName(AnhSP.FileName));
                AnhSP.SaveAs(path);
                sanPham.AnhSP = AnhSP.FileName;
            }
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaDMSP = new SelectList(db.DMSPs, "MaDMSP", "TenDMSP", sanPham.MaDMSP);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyGiaDung/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyGiaDung.Models;
using PagedList;

namespace QuanLyGiaDung.Controllers
{
    public class TinTucsController : Controller
    {
        private QuanLyGiaDung2Entities db = new QuanLyGiaDung2Entities();

        // GET: TinTucs
        public ActionResult Index(string searchString, int? page)
        {
            var links = from l in db.TinTucs // lấy toàn bộ liên kết
                        select l;

            if (!String.IsNullOrEmpty(searchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
            {
                links = links.Where(s => s.TenTinTuc.Contains(searchString)); //lọc theo chuỗi tìm kiếm
            }
            if (page == null) page = 1;
            links = links.OrderBy(x => x.TenTinTuc);
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(links.ToPagedList(pageNumber, pageSize)); //trả về kết quả
        }

        // GET: TinTucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: TinTucs/Create
        public ActionResult Create()
        {
            ViewBag.MaDMTT = new SelectList(db.DMTinTucs, "MaDMTT", "TenDMTT");
            return View();
        }

        // POST: TinTucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(HttpPostedFileBase AnhTinTuc, TinTuc tinTuc)
        {
            if (AnhTinTuc != null)
            {
                string p = Path.Combine(Server.MapPath("~/Anh"), Path.GetFileName(AnhTinTuc.FileName));
                AnhTinTuc.SaveAs(p);
                tinTuc.AnhTinTuc = AnhTinTuc.FileName;
            }
            if (ModelState.IsValid)
            {
                db.TinTucs.Add(tinTuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tinTuc);
        }

        // GET: TinTucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDMTT = new SelectList(db.DMTinTucs, "MaDMTT", "TenDMTT", tinTuc.MaDMTT);
            return View(tinTuc);
        }

        // POST: TinTucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(HttpPostedFileBase AnhTinTuc, TinTuc tinTuc)
        {
            if (AnhTinTuc != null)
            {
                string p = Path.Combine(Server.MapPath("~/Anh"), Path.GetFileName(AnhTinTuc.FileName));
                AnhTinTuc.SaveAs(p);
                tinTuc.AnhTinTuc = AnhTinTuc.FileName;
            }
            if (ModelState.IsValid)
            {
                db.Entry(tinTuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                db.TinTucs.Add(tinTuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tinTuc);
        }

        // GET: TinTucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: TinTucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyGiaDung/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Quản Lý Cửa Hàng Đồ Gia Dụng Nhà Việt</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>It.Next - IT Service Responsive Html Theme</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- site icons -->
    <link rel="icon" href="images/fevicon/fevicon.png" type="image/gif" />
    <!-- bootstrap css -->
    <link rel="stylesheet" href="~/Theme/css/bootstrap.min.css" />
    <!-- Site css -->
    <link rel="stylesheet" href="~/Theme/css/style2.css" />
    <!-- responsive css -->
    <link rel="stylesheet" href="~/Theme/css/responsive.css" />
    <!-- colors css -->
    <link rel="stylesheet" href="~/Theme/css/colorss1.css" />
    <!-- custom css -->
    <link rel="stylesheet" href="~/Theme/css/custom.css" />
    <!-- wow Animation css -->
    <link rel="stylesheet" href="~/Theme/css/animate.css" />
    @*dropdownlist css
    <link rel="stylesheet" href="~/Theme/css/dropdown.css" />*@
    <!-- revolution slider css -->
    <link rel="stylesheet" type="text/css" href="revolution/css/settings.css" />
    <link rel="stylesheet" type="text/css" href="revolution/css/layers.css" />
    <link rel="stylesheet" type="text/css" href="revolution/css/navigation.css" />
    <script src="~/Plugin/ckeditor/ckeditor.js" type="text/javascript"></script>
    <script src="~/Plugin/ckfinder/ckfinder.js" type="text/javascript"></script>
    <!-- header -->


</head>
<body>
    <header id="default_header" class="header_style_1">
        <!-- header top -->
        <div class="header_top">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <div class="full">
                            <div class="topbar-left">
                                <ul class="list-inline">
                                    <li> <span class="topbar-label"><i class="fa  fa-home"></i></span> <span class="topbar-hightlight">235 Hoàng Quốc Việt Street</span> </li>
                                    <li> <span class="topbar-label"><i class="fa fa-envelope-o"></i></span> <span class="topbar-hightlight"><a href="mailto:info@yourdomain.com">giadungnhaviet.com</a></span> </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 right_section_header_top">
                        <div class="float-left">
                            <div class="social_icon">
                                <ul class="list-inline">
                                    <li><a class="fa fa-facebook" href="https://www.facebook.com/" title="Facebook" target="_blank"></a></li>
                                    <li><a class="fa fa-google-plus" href="https://plus.google.com/" title="Google+" target="_blank"></a></li>
                                    <li><a class="fa fa-twitter" href="https://twitter.com" title="Twitter" target="_blank"></a></li>
                                    <li><a class="fa fa-linkedin" href="https://www.linkedin.com" title="LinkedIn" target="_blank"></a></li>
                                    <li><a class="fa fa-instagram" href="https://www.instagram.com" title="Instagram" target="_blank"></a></li>
                                </ul>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- end header top -->
        <!-- header bottom -->
        <div class="header_bottom">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                        <!-- logo start -->
                        <div class="logo" > <a href="it_home.html"><img src="~/images/unnamed.jpg" " alt="logo "" /></a> </div>
                        <!-- logo end -->
                    </div>
                    <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                        <!-- menu start -->
                        <div class="menu_side">
                            <div id="navbar_menu">
                                <ul class="first-ul">
                                    <li>
                                    <li class="mr-4">@Html.ActionLink("Home", "Index", "Home")</li>
                                    <li class="mr-4">@Html.ActionLink("Nhân Viên", "Index", "NhanViens")</li>
                                    <li class="mr-4">
                                    <li class="mr-4">
                                        <a href="#">Quản Lý Sản Phẩm</a>
                                        <ul>
                                            <div>@Html.ActionLink("Danh Mục Sản Phẩm ", "Index", "DMSPs")</div>
                                            <div>@Html.ActionLink("Sản Phẩm", "Index", "SanPhams")</div>
                                        </ul>
                                    </li>

                                    <li class="mr-4"> @Html.ActionLink("Khách Hàng", "Index", "KhachHangs")</li>
                                    <li class="mr-4">
                                        <a href="#">Quản Lý Tin Tức</a>
                                        <ul>
                                            <div>@Html.ActionLink("Tin Tức", "Index", "TinTucs")</div>
                                            <div>@Html.ActionLink("Danh Mục Tin Tức", "Index", "DMTinTucs")</div>
                                        </ul>
                                    </li>
                                    
                                </ul>
                            </div>
                            <div class="search_icon">
                                <ul>
                                    <li><a href="#" data-toggle="modal" data-target="#search_bar"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- menu end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- header bottom end -->
    </header>



   
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
 @*footer 
<footer class="footer_style_2">
    <div>
        <div class="row">
            
            <div class="footer_blog" style="margin-left: 200px;">
                <div class="row">
                    <div class="col-md-3">
                        <div class="main-heading left_text">
                            <h2>It Next Theme</h2>
                        </div>
                        <p>Tincidunt elit magnis nulla facilisis. Dolor sagittis maecenas. Sapien nunc amet ultrices, dolores sit ipsum velit purus aliquet, massa fringilla leo orci.</p>
                        <ul class="social_icons">
                            <li class="social-icon fb"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li class="social-icon tw"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li class="social-icon gp"><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <div class="main-heading left_text">
                            <h2>Additional links</h2>
                        </div>
                        <ul class="footer-menu">
                            <li><a href="it_about.html"><i class="fa fa-angle-right"></i> About us</a></li>
                            <li><a href="it_term_condition.html"><i class="fa fa-angle-right"></i> Terms and conditions</a></li>
                            <li><a href="it_privacy_policy.html"><i class="fa fa-angle-right"></i> Privacy policy</a></li>
                            <li><a href="it_news.html"><i class="fa fa-angle-right"></i> News</a></li>
                            <li><a href="it_contact.html"><i class="fa fa-angle-right"></i> Contact us</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <div class="main-heading left_text">
                            <h2>Services</h2>
                        </div>
                        <ul class="footer-menu">
                            <li><a href="it_data_recovery.html"><i class="fa fa-angle-right"></i> Data recovery</a></li>
                            <li><a href="it_computer_repair.html"><i class="fa fa-angle-right"></i> Computer repair</a></li>
                            <li><a href="it_mobile_service.html"><i class="fa fa-angle-right"></i> Mobile service</a></li>
                            <li><a href="it_network_solution.html"><i class="fa fa-angle-right"></i> Network solutions</a></li>
                            <li><a href="it_techn_support.html"><i class="fa fa-angle-right"></i> Technical support</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3" style="float:right;">
                        <div class="main-heading left_text">
                            <h2>Contact us</h2>
                        </div>
                        <p>
                            : Số 10 ngõ 20 Phố Nghĩa Đô,<br>
                             Phường Nghĩa Đô, Quận Cầu Giấy, Hà Nội<br>
                            <span style="font-size:18px;"><a href="tel:+9876543210">+987 654 3210</a></span>
                        </p>
                        <div class="footer_mail-section">
                            <form>
                                <fieldset>
                                    <div class="field">
                                        <input placeholder="Email" type="text">
                                        <button class="button_custom"><i class="fa fa-envelope" aria-hidden="true"></i></button>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cprt">
                <p>ItNext © Copyrights 2019 Design by html.design</p>
            </div>
        </div>
    </div>
</footer>*@

<!-- end footer -->

</html>